export const headerData = [
  { src: "/assets/images/redo.svg", alt: "Redo", component: "" },
  { src: "/assets/images/redo2.svg", alt: "Redo 2", component: "" },
  { src: "/assets/images/Tabs2.svg", alt: "Tabs 2", component: "" },
  { src: "/assets/images/tabs.svg", alt: "Tabs", component: "" },
  {
    src: "/assets/images/colorfilter.svg",
    alt: "Color Filter",
    text: "Fill",
    component: "dropdown",
    checkbox: false,
    icons: false,
    onlyLabels: false,
    colorPicker: true,
  },
  {
    src: "/assets/images/mask.svg",
    alt: "Mask",
    text: "Border",
    component: "",
  },
  {
    src: "/assets/images/mouse-circle.svg",
    alt: "Mouse Circle",
    text: "Cursor",
    component: "",
  },
  {
    src: "/assets/images/unlock.svg",
    alt: "Unlock",
    text: "Unlock",
    component: "",
  },
  {
    src: "/assets/images/tag-cross.svg",
    alt: "Tag Cross",
    text: "Delete",
    component: "",
  },
  {
    src: "/assets/images/textalign-left.svg",
    alt: "Text Align",
    text: "Align",
    extraSrc: "/assets/images/arrow-down.svg",
    component: "dropdown",
    options: [
      { label: "align left", icon: "/assets/images/align-left.svg" },
      {
        label: "align horizontal",
        icon: "/assets/images/align-horizontally.svg",
      },
      { label: "align right", icon: "/assets/images/align-right.svg" },
      { label: "align top", icon: "/assets/images/align-bottom.svg" },
      {
        label: "align vertical",
        icon: "/assets/images/align-horizontally.svg",
      },
      { label: "align bottom", icon: "/assets/images/align-vertically.svg" },
    ],
    checkbox: false,
    icons: true,
    onlyLabels: false,
  },
  {
    src: "/assets/images/slider-horizontal.svg",
    alt: "Slider Horizontal",
    text: "Distribute",
    extraSrc: "/assets/images/arrow-down.svg",
    component: "dropdown",
    options: [
      { label: "distribute left", icon: "/assets/images/distribute_left.svg" },
      {
        label: "distribute horizontal",
        icon: "/assets/images/slider-horizontal.svg",
      },
      {
        label: "distribute right",
        icon: "/assets/images/distribute_right.svg",
      },
      { label: "distribute top", icon: "/assets/images/distribute_top.svg" },
      {
        label: "distribute vertical",
        icon: "/assets/images/slider-vertical.svg",
      },
      {
        label: "distribute bottom",
        icon: "/assets/images/Group.svg",
      },
    ],
    checkbox: false,
    icons: true,
    onlyLabels: false,
  },
  {
    src: "/assets/images/layer.svg",
    alt: "Layer",
    text: "Layers",
    extraSrc: "/assets/images/arrow-down.svg",
    component: "dropdown",
    options: [
      {
        label: "show all layers",
        icon: "/assets/images/eye.svg",
        checkbox: false,
      },
      {
        label: "background layer only",
        icon: "/assets/images/layer.svg",
        checkbox: false,
      },
      { label: "content layer", icon: null, checkbox: true },
      { label: "background layer", icon: null, checkbox: true },
      { label: "help layer", icon: null, checkbox: true },
      {
        label: "create layer",
        icon: "/assets/images/add-square.svg",
        checkbox: false,
      },
      {
        label: "delete layer",
        icon: "/assets/images/trash.svg",
        checkbox: false,
      },
    ],
    checkbox: true,
    icons: true,
    onlyLabels: false,
  },
  {
    src: "/assets/images/grid-edit.svg",
    alt: "Grid Edit",
    text: "View",
    component: "dropdown",
    options: [
      { label: "ruler", icon: null },
      { label: "snap to", icon: null },
      { label: "grid", icon: null },
      { label: "help layer", icon: null },
      { label: "comment", icon: null },
    ],
    checkbox: true,
    icons: true,
    onlyLabels: false,
  },
  {
    src: "/assets/images/lamp-charge.svg",
    alt: "Lamp Charge",
    text: "Ladder",
    component: "dropdown",
    checkbox: false,
    icons: false,
    onlyLabels: true,
    ladder: true,
  },
];
